/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:a175b32d-07b1-4a2a-87c0-baddfce590b4",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_oCOZrL4u9",
    "aws_user_pools_web_client_id": "12blsatde6iid0fi2mv7oogjo7",
    "oauth": {
        "domain": "dev-petrot-anyupp-admin.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "openid"
        ],
        "redirectSignIn": "http://localhost:4200/admin/dashboard",
        "redirectSignOut": "http://localhost:4200/auth/login",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://elty5sz4bzb7ji6snwmsq4b3jy.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jxkkzgt5zzbihm2hwikhhm2gi4"
};


export default awsmobile;
