FROM public.ecr.aws/bitnami/node:14

WORKDIR /

COPY .serverless-2/report-generator.zip /

RUN unzip /report-generator.zip \
  && rm /report-generator.zip \
  && npm install aws-sdk

ENTRYPOINT node /lib/lambda/report-generator/index.js
