FROM node:14-alpine

WORKDIR /

COPY .serverless/rkeeper-product-processor.zip /

RUN unzip /rkeeper-product-processor.zip \
  && rm rkeeper-product-processor.zip \
  && npm install aws-sdk

ENTRYPOINT node /lib/lambda/rkeeper-product-processor/index.js
