FROM node:14-alpine

WORKDIR /

COPY .serverless/report-generator.zip /

RUN unzip /report-generator.zip \
  && rm /report-generator.zip \
  && npm install aws-sdk

ENTRYPOINT node /lib/lambda/report-generator/index.js
