version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["angular"]

[[analyzers]]
name = "shell"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true
