projects:
  main:
    schemaPath: amplify/backend/api/anyuppbackend/build/schema.graphql
    includes:
      - ../../libs/crud-gql/api/src/lib/generated/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: ../../libs/crud-gql/api/src/lib/generated/api.ts
        docsFilePath: ../../libs/crud-gql/api/src/lib/generated/graphql
        region: eu-west-1
        apiId: null
        maxDepth: 6
  anyuppbackend:
    schemaPath: ../../libs/crud-gql/api/src/lib/generated/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
