FROM cirrusci/flutter:3.0.4

RUN flutter doctor

COPY apps/anyupp-mobile anyupp-mobile

#RUN cd anyupp-mobile \
#  && flutter pub get \
#  && flutter build apk \
#  && cd .. \
#  && rm -rf anyupp-mobile \

RUN  sdkmanager "platform-tools" "platforms;android-29" "emulator" "system-images;android-29;default;x86" \
  && echo "no" | avdmanager --verbose create avd --force --name "int_test" --package "system-images;android-29;default;x86" --tag "default" --abi "x86"


