/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://jh3b5onvtffjnb6ptvaaoyrrr4.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-nufi3wftrrblnm5ukf5tn7f6qy",
    "aws_cognito_identity_pool_id": "eu-west-1:942d39b6-c1f1-4ed9-95f4-6cd9eeef821a",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_B6tKQTDzc",
    "aws_user_pools_web_client_id": "3u0u2n4inn1spfep5r9q1p0rk3",
    "oauth": {
        "domain": "dev-anyupp-backend-with-storage-admin.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "openid"
        ],
        "redirectSignIn": "http://localhost:4200/admin/dashboard",
        "redirectSignOut": "http://localhost:4200/auth/login",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "amplifyadminaac0cb222bde46fb87de97940d38ecc894143-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
