/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:83b11bef-b255-462c-ae77-680592eb34a8",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_uQinis9TS",
    "aws_user_pools_web_client_id": "4hq082sd8sngpd5ei6gueh2h7s",
    "oauth": {
        "domain": "dev-anyupp-backend-admin.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "openid"
        ],
        "redirectSignIn": "http://localhost:4200/admin/dashboard,https://dev.admin.anyupp-backend.anyupp.com/admin/dashboard",
        "redirectSignOut": "http://localhost:4200/auth/logout,https://dev.admin.anyupp-backend.anyupp.com/auth/logout",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://ygzl3hlvujcrvlmmnhnhjvlpiu.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-z7merrmw6reg3kppjre3e3dngy",
    "aws_user_files_s3_bucket": "anyuppbackend7e940fce5ea84a60a055e26c9088319e192945-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
