projects:
  amplifyadmin:
    schemaPath: >-
      Users/tomi/Dev/web/localhost/bitgap/cyberg/anyupp/libs/admin/amplify/src/lib/graphql/schema.json
    includes:
      - ../..libs/admin/amplify/src/lib/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: ../../libs/admin/amplify/src/lib/api.service.ts
        docsFilePath: ../..libs/admin/amplify/src/lib/graphql
        maxDepth: 10
extensions:
  amplify:
    version: 3
