projects:
  anyuppbackend:
    schemaPath: amplify/backend/api/anyuppbackend/build/schema.graphql
    includes:
      - ../../libs/admin/amplify-api/src/lib/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: ../../libs/admin/amplify-api/src/lib/generated/api.ts
        docsFilePath: ../../libs/admin/amplify-api/src/lib/generated/graphql
        region: eu-west-1
        apiId: null
        maxDepth: 10
extensions:
  amplify:
    version: 3
