export enum EOrderStatus {
  NONE = 'NONE',
  PLACED = 'PLACED',
  PROCESSING = 'PROCESSING',
  READY = 'READY',
  SERVED = 'SERVED',
  WAITING_FOR_PAYMENT = 'WAITING_FOR_PAYMENT',
  PAID = 'PAID',
  // RECEIVED = 'RECEIVED',
  FAILED = 'FAILED',
  REJECTED = 'REJECTED',
}
