# include: package:effective_dart/analysis_options.yaml
include: package:pedantic/analysis_options.1.8.0.yaml
# include: package:lints/recommended.yaml
analyzer:
  exclude:
    [
      build/**,
      lib/graphql/generated/**.dart,
      lib/**.g.dart,
      test/graphql/generated/**.dart,
    ]
  strong-mode:
    implicit-casts: true
  errors:
    unnecessary_import: ignore
    unnecessary_non_null_assertion: ignore
linter:
  rules:
