# include: package:effective_dart/analysis_options.yaml

include: package:pedantic/analysis_options.1.8.0.yaml

analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: true

linter:
  rules:
    - camel_case_types
    - unnecessary_null_checks
    - avoid_equals_and_hash_code_on_mutable_classes
