name: anyupp
description: Anyupp

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.0+1050000

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  amazon_cognito_identity_dart_2: ^3.0.1
  anchor_scroll_controller: ^0.4.0
  app_tracking_transparency: ^2.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  awesome_card: ^1.1.5
  badges: ^2.0.1
  bloc: ^8.1.0
  cached_network_image: ^3.2.2
  catcher: ^0.6.6
  connectivity_plus: ^2.3.8
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.3
  dio: ^4.0.4
  double_back_to_close_app: ^2.0.1
  equatable: ^2.0.5
  expandable: ^5.0.1
  flutter_bloc: ^8.1.1
  flutter_local_notifications: ^9.1.5
  flutter_inappwebview: ^5.4.4+2
  flutter_slidable: ^0.6.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^1.1.5
  form_field_validator: ^1.1.0
  geolocator: ^9.0.2
  get_it: ^7.1.3
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.1
  artemis: 7.9.0-beta
  graphql_flutter: ^5.1.0
  gql_dio_link: ^0.2.2
  intl: ^0.17.0
  logger: ^1.1.0
  lottie: ^1.4.3
  location_permissions: ^4.0.0
  mask_text_input_formatter: ^2.4.0
  package_info: ^2.0.2
  path_provider: ^2.0.2
  pull_to_refresh: ^2.0.0
  qr_code_scanner: ^1.0.1
  rxdart: ^0.27.0
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  stripe_sdk: 5.0.0-nullsafety.0
  uni_links2: ^0.6.0
  url_launcher: ^6.1.6
  uuid: ^3.0.4
  open_file: ^3.2.1
  in_app_update: ^3.0.0 #for android
  upgrader: ^4.6.1
  carousel_slider: ^4.0.0
  tinycolor2: ^3.0.1
  sensors_plus: ^1.4.0
  animated_toggle_switch: ^0.5.2
  bubble_box: ^0.5.3
  modal_bottom_sheet: ^2.1.2
  functional_data: ^1.0.0
  flutter_riverpod: ^1.0.4
  firebase_messaging: ^13.0.4
  riverbloc: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_driver:
  #   sdk: flutter
  test: any
  bloc_test: ^9.1.0
  pedantic: ^1.11.1
  integration_test:
    #    sdk: flutter
  effective_dart: ^1.3.2
  flutter_launcher_icons: ^0.10.0
  build_runner: ^2.2.1
  json_annotation: ^4.7.0
  json_serializable: ^6.4.1
  faker: ^2.0.0
  http_mock_adapter: ^0.3.2
  mockito: ^5.3.2
  mocktail: ^0.3.0
  functional_data_generator: ^1.1.4
  # dependency_validator: ^3.0.0

# dependency_overrides:
# modal_bottom_sheet: ^2.0.1
#    gql_exec: ^0.3.0
# sqflite: 1.3.0
# analyzer: '0.39.14'

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/launcher_icon/anyupp_black.png'
  adaptive_icon_background: '#000000'
  adaptive_icon_foreground: 'assets/launcher_icon/ic_launcher_foreground.png'

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/lang/
    - assets/icons/
    - assets/android_icons/
    - assets/ios_icons/
    - assets/images/
    - assets/flags/
    - assets/allergens/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 600
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
