name: fa_prev
description: Cyberg's 3FA project app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.34+1034

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  amazon_cognito_identity_dart_2: ^0.1.25+1
  amplify_auth_cognito: <1.0.0
  amplify_datastore: <1.0.0
  amplify_flutter: <1.0.0
  animated_background: ^1.0.5
  apple_sign_in: ^0.1.0
  awesome_card: ^1.1.0
  badges: ^1.1.1
  barcode_scan: ^3.0.1
  cached_network_image: ^2.2.0+1
  camera: ^0.5.8+7
  catcher: ^0.3.23
  cloud_functions: ^0.5.0
  connectivity: ^0.4.4
  cupertino_icons: ^0.1.3
  double_back_to_close_app: ^1.2.0
  equatable: ^1.2.5
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.15.5+3
  firebase_core: ^0.4.4+3
  firebase_database: ^3.1.5
  firebase_dynamic_links: ^0.5.3
  firebase_ml_vision: ^0.9.7
  firebase_storage: ^3.1.6
  flutter_bloc: ^6.1.1
  flutter_dotenv: ^2.1.0
  flutter_inappwebview: ^4.0.0+4
  flutter_local_notifications: ^1.4.4+2
  flutter_login_facebook: ^0.4.1
  flutter_sequence_animation: ^3.0.1
  flutter_staggered_animations: ^0.1.2
  flutter_svg: ^0.19.0
  form_field_validator: ^1.0.1
  geolocator: ^6.1.8
  get_it: ^4.0.2
  google_fonts: ^1.1.0
  google_maps_flutter: ^0.5.28+1
  google_sign_in: ^4.4.6
  gql: '>=0.7.3 <1.0.0'
  graphql_flutter: ^3.1.0
  intl: ^0.16.1
  json_serializable: ^3.0.0
  lottie: ^0.7.0+1
  mask_text_input_formatter: ^1.0.7
  meta: '>=1.0.0 <2.0.0'
  package_info: '>=0.4.3 <2.0.0'
  permission_handler: ^5.0.1+1
  rxdart: ^0.24.1
  shared_preferences: ^0.5.8
  stripe_sdk: <=3.2.0
  tflite: ^1.1.1
  uni_links: ^0.4.0
  url_launcher: ^5.7.4
  webview_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  artemis: ^5.1.0 # to generate dart classes from graphql queries
  build_runner: ^1.5.0 # required by artemis
  flutter_launcher_icons: ^0.8.0
  effective_dart: ^1.0.0

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/launcher_icon/anyupp_black.png'
  adaptive_icon_background: '#000000'
  adaptive_icon_foreground: 'assets/launcher_icon/ic_launcher_foreground.png'

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/lang/
    - assets/icons/
    - assets/images/
    - assets/flags/
    - assets/models/
    - env/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Light.ttf
  #       - asset: assets/fonts/Montserrat-LightItalic.ttf
  #         style: italic
  #   - family: SF-Pro-Display-Bold
  #     fonts:
  #       - asset: assets/fonts/SF-Pro-Display-Bold.ttf
