projects:
  amplifyadmin:
    schemaPath: amplify/backend/api/amplifyadmin/build/schema.graphql
    includes:
      - ../../libs/shared/amplify/src/lib/documents/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: ../../libs/shared/amplify/src/lib/api.ts
        docsFilePath: ../../libs/shared/amplify/src/lib/documents
        region: eu-west-1
        apiId: null
        maxDepth: 5
extensions:
  amplify:
    version: 3
