/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-west-1',
  aws_appsync_graphqlEndpoint:
    'https://jh3b5onvtffjnb6ptvaaoyrrr4.appsync-api.eu-west-1.amazonaws.com/graphql',
  aws_appsync_region: 'eu-west-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-nufi3wftrrblnm5ukf5tn7f6qy',
  aws_cognito_region: 'eu-west-1',
  aws_user_pools_id: 'eu-west-1_uQinis9TS',
  aws_user_pools_web_client_id: '4hq082sd8sngpd5ei6gueh2h7s',
  oauth: {
    domain: 'dev-anyupp-backend-admin.auth.eu-west-1.amazoncognito.com',
    scope: ['openid'],
    redirectSignIn: 'http://localhost:4200/admin/dashboard',
    redirectSignOut: 'http://localhost:4200/auth/login',
    responseType: 'code',
  },
  federationTarget: 'COGNITO_USER_POOLS',
};

export default awsmobile;
