org: anyupp
service: anyupp-crud-infra
configValidationMode: error
frameworkVersion: ^2.16.1

plugins:
  - serverless-bundle
  - serverless-offline

package:
  individually: true

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Name of the SST app that's deploying our infrastructure
  sstApp: anyupp-crud-infra
  bundle:
    packager: yarn
    linting: false
    sourcemaps: true
    caching: true
    concurrency: 1
    esbuild: true

  offline:
    useChildProcesses: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  custom-resolvers:
    handler: lib/lambda/custom-resolvers/index.handler
