name: CI

on: [push]

jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@dev

      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'dev:libs/anyupp-gql/backend/src/graphql/schema/anyupp-api.graphql'
      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'dev:libs/crud-gql/backend/src/graphql/crud-api.graphql'
