org: anyupp
service: anyupp-backend
configValidationMode: error
frameworkVersion: ^2.16.1

plugins:
  - serverless-bundle
  - serverless-dotenv-plugin

package:
  individually: true

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Name of the SST app that's deploying our infrastructure
  sstApp: ${self:custom.stage}-anyupp-backend
  bundle:
    packager: yarn
    linting: false

  offline:
    useChildProcesses: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: #{AWS::Region}

functions:
  graphql-api:
    handler: lib/appsync/graphql-api/index.handler

  auto-delete-bucket:
    handler: lib/lambda/auto-delete-bucket/index.handler
